components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Tipo de error
          example: "Bad Request"
        message:
          type: string
          description: Mensaje descriptivo del error
          example: "El campo 'name' es requerido"

    ValidationError:
      type: object
      properties:
        error:
          type: string
          example: "Validation Error"
        message:
          type: string
          example: "Los datos proporcionados no son válidos"
        details:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                example: "email"
              message:
                type: string
                example: "El email no es válido"

    NotFoundError:
      type: object
      properties:
        error:
          type: string
          example: "Not Found"
        message:
          type: string
          example: "El recurso solicitado no existe"

    UnauthorizedError:
      type: object
      properties:
        error:
          type: string
          example: "Unauthorized"
        message:
          type: string
          example: "API key inválida o no proporcionada"

    ConflictError:
      type: object
      properties:
        error:
          type: string
          example: "Conflict"
        message:
          type: string
          example: "Ya existe una reserva en ese horario"

  responses:
    BadRequest:
      description: Solicitud inválida
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: No autorizado - API key inválida o no proporcionada
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnauthorizedError'

    NotFound:
      description: Recurso no encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundError'

    ValidationError:
      description: Error de validación
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'

    ConflictError:
      description: Conflicto - El recurso ya existe o hay conflicto de horarios
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConflictError'

    InternalServerError:
      description: Error interno del servidor
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
