paths:
  /health:
    get:
      tags:
      - Health
      summary: Verificar estado del servidor
      description: Endpoint para verificar que el servidor está funcionando correctamente y puede conectarse a la base de datos
      security: []
      responses:
        '200':
          description: Servidor funcionando correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"
                  message:
                    type: string
                    example: "Server is running"
                  timestamp:
                    type: string
                    format: date-time
                  environment:
                    type: string
                    example: "development"
                  database:
                    type: string
                    enum: [ connected, disconnected ]
                    example: "connected"
                  version:
                    type: string
                    example: "v20.10.0"
