export const ERROR_CODES = {
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  RESERVATION_CREATE_FAILED: 'RESERVATION_CREATE_FAILED',
  RESERVATION_UPDATE_FAILED: 'RESERVATION_UPDATE_FAILED',
  RESERVATION_DELETE_FAILED: 'RESERVATION_DELETE_FAILED',
  RESERVATION_FETCH_FAILED: 'RESERVATION_FETCH_FAILED',
  RESERVATION_SCHEDULING_CONFLICT: 'RESERVATION_SCHEDULING_CONFLICT',
  RESERVATION_MAX_LIMIT_REACHED: 'RESERVATION_MAX_LIMIT_REACHED',
  RESERVATION_INVALID_TIME: 'RESERVATION_INVALID_TIME',
  RESERVATION_MISSING_FIELDS: 'RESERVATION_MISSING_FIELDS',

  SPACE_NOT_FOUND: 'SPACE_NOT_FOUND',
  SPACE_CREATE_FAILED: 'SPACE_CREATE_FAILED',
  SPACE_UPDATE_FAILED: 'SPACE_UPDATE_FAILED',
  SPACE_DELETE_FAILED: 'SPACE_DELETE_FAILED',
  SPACE_FETCH_FAILED: 'SPACE_FETCH_FAILED',
  SPACE_MISSING_FIELDS: 'SPACE_MISSING_FIELDS',

  PLACE_NOT_FOUND: 'PLACE_NOT_FOUND',
  PLACE_CREATE_FAILED: 'PLACE_CREATE_FAILED',
  PLACE_UPDATE_FAILED: 'PLACE_UPDATE_FAILED',
  PLACE_DELETE_FAILED: 'PLACE_DELETE_FAILED',
  PLACE_FETCH_FAILED: 'PLACE_FETCH_FAILED',
  PLACE_MISSING_FIELDS: 'PLACE_MISSING_FIELDS',

  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
