version: "3.8"

services:
  postgres-test:
    image: postgres:16-alpine
    container_name: coworking-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coworking_test
    ports:
      - "5433:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: coworking-api-test
    depends_on:
      postgres-test:
        condition: service_healthy
    environment:
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@postgres-test:5432/coworking_test
      API_KEY: test_api_key
      PORT: 3000
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm run db:setup && npm run test:e2e"

volumes:
  postgres-test-data:
